### ISSUE TITLE
Is it possible to perform LoRA fine-tuning on SPAD?

### ISSUE THREAD

**Issue by ZiyiZhang27** [yashkant/spad#12]
Hi there, congrats on this awesome work! I was wondering if it’s feasible to perform LoRA fine-tuning on SPAD. If it is, could you kindly share any specific considerations or recommended steps? Thank you so much!

**Comment by yashkant** [comment]
hi @ZiyiZhang27, 

i believe it should be possible to finetune LoRAs on top of SPAD.  [minLoRA](https://github.com/cccntu/minLoRA) could be a useful option.

since spad is not integrated into [diffusers](https://github.com/huggingface/diffusers) it could be difficult to directly apply [peft](https://github.com/huggingface/peft) to it? although, i could be wrong here.

at some point @jadechoghari was working to add spad to diffusers, however we hit a blocker, you can see this [issue](https://github.com/yashkant/spad/issues/9) for that.

on the side of training it, you can look into [peft training on stable diffusion](https://github.com/huggingface/peft/blob/main/examples/stable_diffusion/train_dreambooth.py) for various hyperparameter settings. 

hope this helps!
