### ISSUE TITLE
Some questions about the infer code.

### ISSUE THREAD

**Issue by yiboz2001** [yashkant/spad#5]
Hello! 
Thanks for your open-source work~   I have some questions after trying the infer code.
1. What does the "[tdv]" token mean, which is added to the original caption?  It seems not to be mentioned in the paper.
2. Can it generate results of zero elev degree? The default value is 45 degrees, and I meet code errors when I change the value to  0 directly.
Looking for your reply!

**Comment by yashkant** [comment]
hi, thanks for checking out spad!

1. we appended the "[tdv]" token to all captions during multiview training. this provides an additional signal through text that the domain of the new data is slightly different from single view training that was performed previously (on laion). 

2. i believe you maybe looking for 90-degree elevation, since 0-degree would place all the cameras at the same location (on z-axis). [here's the camera conversion equations](https://quantummechanics.ucsd.edu/ph130a/130_notes/node216.html) that we follow, and [here's the corresponding code](https://github.com/yashkant/spad/blob/main/spad/geometry.py#L248). i believe you could try setting the elevation to 90-degrees, and see if that generates the right results. 

hope this helps!
